version: "3.7"

services:
  # Load Balancer Nginx
  # Ponto de entrada para todas as requisições, que serão distribuídas para o backend.
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - app1
      - app2
    networks:
      - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  # Primeira instância do nosso backend em C#.
  app1:
    build: .
    image: rinha-backend-2025-cs
    hostname: app1
    depends_on:
      - redis
      - payment-processor-default
      - payment-processor-fallback
    networks:
      - rinha-backend-network
      - payment-processor-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  # Segunda instância do nosso backend em C#.
  app2:
    build: .
    image: rinha-backend-2025-cs
    hostname: app2
    depends_on:
      - redis
      - payment-processor-default
      - payment-processor-fallback
    networks:
      - rinha-backend-network
      - payment-processor-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  # Serviço Redis para cache e persistência.
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  # Service Payment Processor Default (fornecido pela Rinha)
  payment-processor-default:
    image: zanfranceschi/payment-processor:amd64-20250728111932
    container_name: payment-processor-default
    hostname: payment-processor-default
    networks:
      - payment-processor-network
      - payment-processor-db-network
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - "8001:8080"
    depends_on:
      - payment-processor-default-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.25"
          memory: "42MB"

  # Banco de dados do Payment Processor Default
  payment-processor-default-db:
    image: postgres:17-alpine
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db
    networks:
      - payment-processor-db-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./payment-processors/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  # Service Payment Processor Fallback (fornecido pela Rinha)
  payment-processor-fallback:
    image: zanfranceschi/payment-processor:amd64-20250728111932
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    networks:
      - payment-processor-network
      - payment-processor-db-network
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - "8002:8080"
    depends_on:
      - payment-processor-fallback-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.25"
          memory: "42MB"

  # Banco de dados do Payment Processor Fallback
  payment-processor-fallback-db:
    image: postgres:17-alpine
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db
    networks:
      - payment-processor-db-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./payment-processors/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  rinha-backend-network:
    driver: bridge
  payment-processor-network:
    driver: bridge
  payment-processor-db-network:
    driver: bridge
